config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'teachers/index'
  root 'home#index'

  get 'teachers/teupdates'
  get 'students/stupdates'
  resources :students
  resources :updates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/update.rb
class Update < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def stupdates
    @updates = Update.all.order(created_at: :desc)
  end


  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to teachers_index_path
    else
      render :new
    end
  end

  
   private

  def student_params
    params.require(:student).permit(:name, :roll_no, :my_class)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @students = Student.all
  end

  def teupdates
    @updates = Update.all.order(created_at: :desc)
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  def index
    @updates = Update.all.order(created_at: :desc)
  end


  def new
    @update = Update.new
  end

  def create
    @update = Update.new(update_params)
    if @update.save
      redirect_to teachers_teupdates_path
    else
      render :new
    end
  end

  
   private

  def update_params
    params.require(:update).permit(:title, :body )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="main">
	<div class="homecont">
		<div class="homeimg">
			<img src="https://www.freepnglogos.com/uploads/trophy-png/gold-trophy-shiny-png-0.png">
		</div>
		<div class="hometext">
			<h1>MySchool</h1>
			<hr class="homehr1">
			<p>A Great Place For Education.</p>
	    </div>
	</div>
	
	<div class="homebtn">	    
	    <span><%= link_to "STUDENT", students_index_path, class: "homebtns" %></span>
	    <span><%= link_to "TEACHER", teachers_index_path, class: "homebtnt" %></span>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySchool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_stnavbar.html.erb
<!-- 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>
<script type="text/javascript">
    $(window).scroll(function () {
        if ($(this).scrollTop() > 100) {
            $('.menu').addClass("sticky");
        }
        else {
            $('.menu').removeClass("sticky");

        }
    })
</script>
 -->
    
<div class="sttext">
    <h1><%= link_to "ANAM ASHARA", students_index_path, class: "sth1" %>
        <%= link_to "(Student)", root_path, class: "stsmall" %>  
    </h1>
</div>
<ul class="stmenu">
    <li class="stli"><a href="">ATTENDANCE</a></li>
    <li class="stli"><a href="">VERTUAL CLASSROOM</a></li>
    <li class="stli"><a href="">HOMEWORK</a></li>    
    <li class="stli"><a href="">FEE</a></li>
    <li class="stli"><%= link_to "UPDATES", students_stupdates_path %></li>
    <li class="stli"><a href="">EVENTS</a></li>
    <li class="stli"><a href="">SYLLABUS</a></li>
    <li class="stli"><a href="">TIMETABLE</a></li>
    <li class="stli"><a href="">STUDENTS DETAILS</a></li>
    <li class="stli"><a href="">LEAVE</a></li>
    <li class="stli"><a href="">RESULT</a></li>
</ul>
<!-- <section></section>
<section></section>
<section></section> -->

app/views/students/index.html.erb
<%= render "students/stnavbar" %>

app/views/students/new.html.erb
<%= render "teachers/tenavbar" %>
<div class="stnewcont">
  <h1 class="mb-4">New student</h1>
  <%= form_with model: @student do |form| %>

    <div class="field form-group mb-4">
      <%= form.label :name %><br>
      <%= form.text_field :name, class:"form-control",placeholder:"Name" %>
    </div>

    <div class="field form-group mb-2">
      <%= form.label :roll_no %><br>
      <%= form.text_field :roll_no, class:"form-control",placeholder:"Roll no."  %>
    </div>
    <br>

    <div class="field form-group mb-3">
      <%= form.label :my_class %><br>
      <%= form.text_field :my_class, class:"form-control",placeholder:"Class"  %>
    </div>
    <br>

    <div class="actions">
      <%= form.submit class:'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/students/stupdates.html.erb
<%= render "students/stnavbar" %>
<div class="stupmain">
  <h1>Updates</h1>
  <div class="stupcont">
    <ul>
      <% @updates.each do |update| %>
        <li>
          <strong><%= update.title %></strong><br>
          <%= update.body %><hr class="stuphr">
        </li><br><br>
      <% end %>
    </ul>  
  </div>  
</div>

app/views/teachers/_tenavbar.html.erb
<div class="tetext">
    <h1><%= link_to "MOHD AKIBUDDIN", teachers_index_path, class: "teh1" %>
        <%= link_to "(Teacher)", root_path, class: "tesmall" %>
    </h1>
</div>

<ul class="temenu">
    <li class="teli"><a href="">ATTENDANCE</a></li>
    <li class="teli"><a href="">VERTUAL CLASSROOM</a></li>
    <li class="teli"><%= link_to "UPDATES", teachers_teupdates_path %></li>
    <li class="teli"><%= link_to "NEW STUDENTS", new_student_path %></li>
    <li class="teli"><a href="">EVENTS</a></li>
    <li class="teli"><a href="">TIMETABLE</a></li>
    <li class="teli"><a href="">STUDENTS DETAILS</a></li>
</ul>

app/views/teachers/index.html.erb
<div class="temainind">
 <%= render "teachers/tenavbar" %>
   <div class="tecontainer">
      <div class="row row-cols-5 row-cols-md-5 g-4">   
         <% @students.each do |student| %>
            <div class="col">
               <div class="card text-bg-light mb-3" style="width: 20rem;">
                  <img src="https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpbGR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
                  <div class="card-body">
                   <h4 class="card-title"><strong>Name: </strong><%= student.name %></h4>
                   <h5 class="card-text"><strong>Roll no.: </strong><%= student.roll_no %></h5>
                   <h5 class="card-text"><strong>Class: </strong><%= student.my_class %>th</h5>
                  </div>
               </div>
            </div>
         <% end %>
      </div>
   </div>
</div>

app/views/teachers/teupdates.html.erb
<%= render "teachers/tenavbar" %>
<div class="teupmain">
  <div class="teupform">
     <h1><%= link_to "create new", new_update_path, class:"teupformlink" %></h1>
  </div>

  <div class="teupcont">
    <h1>Updates</h1><br>
    <ul>
      <% @updates.each do |update| %>
        <li>
          <strong><%= update.title %></strong><br>
          <%= update.body %><hr class="teuphr">
        </li><br><br>
      <% end %>
    </ul>
  </div>

</div>    

app/views/updates/index.html.erb
<%= render "students/stnavbar" %>
<h1>Updates</h1>

<ul>
  <% @updates.each do |update| %>
    <li>
      <%= update.title %>
      <%= update.body %>
    </li>
  <% end %>
</ul>     

app/views/updates/new.html.erb
<%= render "teachers/tenavbar" %>
<div class="upnewcont">
	<h1 class="mb-4">New updates</h1>
	<%= form_with model: @update do |form| %>

		<div class="field form-group mb-4">
			<%= form.label :title %><br>
			<%= form.text_field :title, class:"form-control",placeholder:"Title"  %>
		</div>

		<div class="field form-group mb-2">
			<%= form.label :body %><br>
			<%= form.text_area :body, class:"form-control",placeholder:"Body"  %>
		</div>
		<br>
		<div class="actions">
			<%= form.submit class:'btn btn-secondary'  %>
		</div>
	<% end %>
</div>